---
# Default variables for controller_firewall role
controller_firewall_port: 5000
controller_firewall_protocol: tcp
controller_firewall_hostname: <CHANGEME>
controller_firewall_user: <CHANGEME>
controller_firewall_password: <CHANGEME>
